name: Tests
on:
  pull_request:
    paths-ignore:
      - 'README.md'
  push:
    paths-ignore:
      - 'README.md'

jobs:

  test:
    name: Unit test
    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps:

    - name: Set up Go
      uses: actions/setup-go@v2.1.3
      with:
        go-version: '1.16'
      id: go

    - name: Check out code into the Go module directory
      uses: actions/checkout@v3

    - name: Get dependencies
      run: |
        go mod download

    - name: Acceptance tests
      timeout-minutes: 10
      env:
        TF_ACC: "1"
        QUANT_CLIENT_ID: ${{ secrets.QUANT_CLIENT_ID }}
        QUANT_PROJECT: ${{ secrets.QUANT_PROJECT }}
        QUANT_TOKEN: ${{ secrets.QUANT_TOKEN }}
      run: |
        go test -v -cover ./
